---
- name: Install sysstat service
  block:
    - name: Install sysstat package
      package:
        name: sysstat
        state: present
    - name: Enable sysstat service
      service:
        name: sysstat
        enabled: true
  become: true

- name: Enable sysstat
  lineinfile:
    path: /etc/default/sysstat
    regexp: '^ENABLED='
    line: 'ENABLED="true"'
    create: true
  when: ansible_os_family == 'Debian'
  become: true

- name: Copy sysstat configuration
  block:
    - name: Set frequency to 1 minute
      copy:
        src: '../files/sysstat-{{ansible_os_family}}.cron'
        dest: /etc/cron.d/sysstat
        owner: root
        group: root
        mode: 0644
        backup: yes
  become: true
