---
- name: Install sysstat service
  block:
    - name: Install sysstat package
      package:
        name: sysstat
        state: present
    - name: Enable sysstat service
      service:
        name: sysstat
        enabled: true
  become: true

- name: Configure sysstat on deb based system
  block:
    - name: Enable sysstat in /etc/default/sysstat
      lineinfile:
        path: /etc/default/sysstat
        regexp: '^ENABLED='
        line: 'ENABLED="true"'
        create: true
    - name: Set frequency to 1 minute
      shell: sed -i -e 's#5-55/10#\*/1#' /etc/cron.d/sysstat
      become: yes
    - name: Restart sysstat service
      service:
        name: sysstat
        state: restarted
  when: ansible_os_family == 'Debian'
  become: true

- name: Configure sysstat on rpm based system
  block:
    - name: Set frequency to 1 minute
      shell: sed -i -e 's#\*/10#\*/1#' /etc/cron.d/sysstat
      become: yes
    - name: Restart sysstat service
      service:
        name: sysstat
        state: restarted
  when: ansible_os_family == 'RedHat'
  become: true
