---
- name: Install sysstat service
  block:
    - name: Install sysstat package
      package:
        name: sysstat
        state: present
    - name: Enable sysstat service
      service:
        name: sysstat
        enabled: true
  become: true

- name: Configure sysstat on deb based system
  block:
    - name: Enable sysstat in /etc/default/sysstat
      lineinfile:
        path: /etc/default/sysstat
        regexp: '^ENABLED='
        line: 'ENABLED="true"'
        create: true
    - name: Set frequency to 1 minute
      copy:
        src: '../files/sysstat-{{ansible_distribution}}'
        dest: /etc/cron.d/sysstat
        owner: root
        group: root
        mode: 0644
        backup: yes
  when: ansible_os_family == 'Debian'
  become: true

- name: Configure sysstat on rpm based system
  block:
    - name: Set frequency to 1 minute
      copy:
        src: '../files/sysstat-{{ansible_distribution}}'
        dest: /etc/cron.d/sysstat
        owner: root
        group: root
        mode: 0644
        backup: yes
  when: ansible_os_family == 'RedHat'
  become: true
