---
- name: Install sysstat service
  block:
    - name: Install sysstat package
      package:
        name: sysstat
        state: present
    - name: Enable sysstat service
      service:
        name: sysstat
        enabled: true
  become: true

- name: Configure sysstat on Debian
  block:
    - name: Enable sysstat in /etc/default/sysstat
      lineinfile:
        path: /etc/default/sysstat
        regexp: '^ENABLED='
        line: 'ENABLED="true"'
        create: true
      become: true
    - name: Set frequency to 1 minute
      replace:
        path: /etc/cron.d/sysstat
        regexp: '(\*\/10[ \*]+)(\s+.*)(debian-sa1.*)'
        replace: '\21\4\5\6'
      become: true
    - name: Restart sysstat service
      service:
        name: sysstat
        state: restarted
      become: true
  when: ansible_distribution == 'Debian'
  become: true

- name: Configure sysstat on CentOS/RH
  block:
    - name: Set frequency to 1 minute
      replace:
        path: /etc/cron.d/sysstat
        regexp: '((\*\/)(10)([ \*]+))(\s+.*)(sa1.*)'
        replace: '\21\4\5\6'
    - name: Restart sysstat service
      service:
        name: sysstat
        state: restarted
  when: ansible_distribution == 'RedHat'
  become: true
