---
- name: Install Docker (RedHat)
  block:
    - name: Add Docker repository
      yum_repository:
        name: docker-ce
        description: Docker CE YUM repo
        baseurl: https://download.docker.com/linux/centos/docker-ce.repo
    - name: Install Docker CE
      yum: name=docker-ce state=present update_cache=yes
  when: ansible_os_family == 'RedHat'
  become: true

- name: Install Docker (Ubuntu)
  block:
    - name: Add Docker apt-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add Docker apt-repository
      apt_repository:
        repo: 'deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable'
        state: present
    - name: Install Docker CE
      apt: name=docker-ce state=present update_cache=yes
  when: ansible_distribution == 'Ubuntu'
  become: true

- name: Enable Docker service
  service: name=docker enabled=true
  become: true
