---
- name: Load operating-system specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_os_family }}.yaml"

- name: Install LF Recommended Tools
  package:
    name: "{{ lf_recommended_tools_packages }}"
    state: latest
  become: yes
