---
- name: Install Google Protobuf Compiler (protobuf)
  block:
    - name: 'Download protobuf {{protobuf_version}}'
      get_url:
        url: https://github.com/google/protobuf/releases/download/v{{protobuf_version}}/protoc-{{protobuf_version}}-linux-x86_64.zip
        dest: /tmp/protobuf-{{protobuf_version}}-linux-x86_64.zip
        checksum: '{{protobuf_checksum}}'

    - name: 'Unarchive protobuf {{protobuf_version}}'
      unarchive:
        src: /tmp/protobuf-{{protobuf_version}}-linux-x86_64.zip
        dest: /tmp/protobuf-{{protobuf_version}}
        remote_src: yes

    - name: Copy Protoc to /usr/local/bin
      command: mv /tmp/protobuf-{{protobuf_version}}/bin/protobuf /usr/local/bin/
      become: true
