---
- name: Install Google Protobuf Compiler (protoc)
  block:
    - name: 'Install protoc {{protoc_version}}'
      unarchive:
        src: https://github.com/google/protobuf/releases/download/v{{protoc_version}}/protoc-{{protoc_version}}-linux-x86_64.zip
        dest: /tmp/protoc-{{protoc_version}}

    - name: Copy Protoc to /usr/local/bin
      command: mv /tmp/protoc-{{protoc_version}}/bin/protoc /usr/local/bin/
      become: true
      become_user: root
