---
- name: Install Google Protobuf Compiler (protobuf)
  block:
    - name: 'Install protobuf {{protobuf_version}}'
      unarchive:
        src: https://github.com/google/protobuf/releases/download/v{{protobuf_version}}/protobuf-{{protobuf_version}}-linux-x86_64.zip
        dest: /tmp/protobuf-{{protobuf_version}}

    - name: Copy Protoc to /usr/local/bin
      command: mv /tmp/protobuf-{{protobuf_version}}/bin/protobuf /usr/local/bin/
      become: true
