---
- name: Install haveged for low entropy rejecting ssh connections
  block:
    - name: Install haveged package
      package: name=haveged state=present
    - name: Enable haveged service
      service: name=haveged enabled=yes
  become: true
